project:
  math:
    \ABalLvl: \BalGroFac{\ALvl}
    \AFunc: \mathrm{A}
    \ALev: A
    \ALevBF: \mathbf{A}
    \ALvl: \mathbf{A}
    \ANrm: A
    \APFac: \text{\pmb{\Thorn}}
    \APRte: \text{\thorn}
    \ARat: A
    \ASS: A
    \ATarg: \check{A}
    \Abve: \bar
    \Age: Z
    \Alive: \mathcal{L}
    \Alt: \grave
    \BE: \BRat^{e}
    \BFunc: \mathrm{B}
    \BLev: B
    \BLevBF: \mathbf{B}
    \BLevE: \BLev^{e}
    \BLevU: \BLev^{u}
    \BLvl: \mathbf{B}
    \BNrm: B
    \BRat: B
    \BRatE: '{B}^{e}'
    \BTarg: \check{B}
    \BTargTarg: \Target{\Target{\BRat}}
    \BU: '{B}^{u}'
    \BalGroFac: \check
    \BalGroRte: \tilde
    \Belw: \ushort
    \CARA: \alpha
    \CDF: \mathcal{F}
    \CE: \CRat^{e}
    \CEndFunc: \mathfrak{C}
    \CFunc: \mathrm{C}
    \CGroOverG: \Upsilon
    \CGroOverR: \Phi
    \CGroPF: \Lambda
    \CGroPS: \chi
    \CLev: C
    \CLevBF: \mathbf{C}
    \CLevE: \CLev^{e}
    \CLevU: \CLev^{u}
    \CLvl: \mathbf{C}
    \CNrm: C
    \CPDV: \text{PDV($C$)}
    \CRRA: \rho
    \CRat: C
    \CRatE: \CRat^{e}
    \CRatU: \CRat^{u}
    \CTarg: \Target{C}
    \CTargE: \CTarg^{\null}
    \CU: \CRat^{u}
    \Chi: \mathrm{X}
    \Cons: C
    \Curr: t
    \DFunc: \mathrm{D}
    \DLev: D
    \DLvl: \mathbf{D}
    \DNrm: D
    \Debt: D
    \Decision: \mathbb{D}
    \Depr: \daleth
    \DeprFac: \daleth
    \DieFac: \pDead
    \DiePrb: \mathsf{D}
    \DiscAlt: \beth
    \DiscAltuAdj: \underline{\underline{\beth}}
    \DiscFac: \beta
    \DiscFacAlt: \beth
    \DiscFacLiv: \underline{\DiscFacRaw}
    \DiscFacRaw: \beta
    \DiscRate: \vartheta
    \DiscRte: \vartheta
    \Discount: \beta
    \Div: D
    \DivGro: \mathrm{G}
    \Dvdnd: \mathbf{D}
    \EEndMap: \mathsf{E}
    \EFunc: \mathrm{E}
    \ELev: E
    \ELvl: \mathbf{E}
    \ENrm: E
    \EPermShkInv: \Ex[\PermShk^{-1}]
    \EPrem: \Phi
    \EVarr: \sigma_{\Risky}^{2}
    \EmpGro: \Xi
    \EpShkInv: \Ex[\pShk^{-1}]
    \EpremLog: \varphi
    \Err: Z
    \Estdr: \sigma_{\risky}
    \Evarr: \sigma_{\risky}^{2}
    \Ex: \mathbb{E}
    \FDist: \mathcal{F}
    \FFunc: \mathrm{F}
    \FLev: F
    \FLvl: \mathbf{F}
    \FNrm: F
    \FP: \mathrm{F}^{\prime}
    \FPP: \mathrm{F}^{\prime\prime}
    \GDPGro: \gimel
    \GDPLev: \pmb{P}
    \GDPRat: P
    \GFunc: \mathrm{G}
    \GLev: G
    \GLvl: \mathbf{G}
    \GPFacNrm: \APFac_{\PermGroFacAdj}
    \GPFacRaw: \APFac_{\PermGroFac}
    \GPRte: \text{\thorn}_{\PermGroRte}
    \GovNW: N
    \GovSpend: X
    \GroFac: \Omega
    \GroRte: \omega
    \HFunc: \mathrm{H}
    \HLev: \pmb{H}
    \HLevBF: \mathbf{H}
    \HLvl: \mathbf{H}
    \HMin: \underline{H}
    \HNrm: H
    \HRat: H
    \Habit: H
    \Ham: \mathcal{H}
    \Hi: \hat
    \Hours: \mathfrak{H}
    \IFunc: \mathrm{I}
    \ILev: I
    \ILvl: \mathbf{I}
    \INrm: I
    \IRat: I
    \ImpG: \Im}_{\PGro
    \ImpR: \Im}_{\Rfree
    \Inc: Y
    \IncUnemp: \mu
    \Inv: I
    \InvEPermShkInv: \underline{\PermShk}
    \InvEpShkInv: \underline{\psi}
    \JFunc: \mathrm{J}
    \JLev: J
    \JLvl: \mathbf{J}
    \JNrm: J
    \KFunc: \mathrm{K}
    \KLev: K
    \KLevBF: \mathbf{K}
    \KLvl: \mathbf{K}
    \KNrm: K
    \KRat: K
    \Kap: K
    \LFunc: \mathrm{L}
    \LGro: \Lambda
    \LLev: L
    \LLevBF: \mathbf{L}
    \LLvl: \mathbf{L}
    \LRat: L
    \Labor: \mathrm{L}
    \Leisure: Z
    \LivFac: \Alive
    \LivPrb: \cancel{\DiePrb}
    \Lo: \check
    \Lvl: \mathbf
    \MBalLvl: \BalGroFac{\MNrm}
    \ME: \MRat^{e}
    \MFunc: \mathrm{M}
    \MLev: M
    \MLevBF: \mathbf{M}
    \MLvl: \mathbf{M}
    \MNrm: M
    \MPC: \kappa
    \MPCE: \MPC^{e}
    \MPCFunc: \pmb{\kappa}
    \MPCP: \pi
    \MPCPPF: \Pi
    \MPCU: \MPC^{u}
    \MPCmax: \bar{\kappa}
    \MPCmaxmax: \bar{\bar{\kappa}}
    \MPCmaxmin: \hat{\underline{\kappa}}
    \MPCmin: \uline{\kappa}
    \MPCminmin: \underline{\kappa}
    \MPS: \lambda
    \MPSFunc: \pmb{lambda}
    \MPSmax: \RPFac
    \MPSmin: \pZero^{1/\CRRA} \RPFac
    \MRat: M
    \MRatE: \MRat^{e}
    \MSS: \breve{M}
    \MU: '{M}^{u}'
    \MaxMPC: \bar{\kappa}
    \MaxMPS: \PatR
    \MaxMaxMPC: \bar{\bar{\kappa}}
    \MaxMinMPC: \hat{\underline{\kappa}}
    \Mean: \mathbb{M}
    \MinMPC: \uline{\kappa}
    \MinMPS: \pZero^{1/\CRRA} \PatR
    \MinMinMPC: \underline{\kappa}
    \Mod: \tilde
    \NFALev: \NLev
    \NFARat: \NRat
    \NFunc: \mathrm{N}
    \NI: Z
    \NLev: N
    \NLvl: \mathbf{N}
    \NRat: N
    \Next: t+1
    \Num: N
    \OFunc: \mathrm{O}
    \OLev: O
    \OLevBF: \mathbf{O}
    \OLvl: \mathbf{O}
    \ORat: O
    \PDV: \mathbb{P}
    \PDies: \mathsf{D}
    \PFunc: \mathrm{P}
    \PGro: \Gamma
    \PGroAdj: \underline{\PGro}
    \PGrouAdj: \underline{\underline{\PGro}}
    \PIHMPC: \varkappa
    \PInc: P
    \PLabor: P
    \PLev: P
    \PLevBF: \mathbf{P}
    \PLives: \cancel{\PDies}
    \PLvl: \mathbf{P}
    \PNrm: P
    \PPDV: \text{PDV($P$)}
    \PShk: \Psi
    \Pareto: \zeta
    \Pat: \text{\pmb{\Thorn}}
    \PatPGro: \text{\pmb{\Thorn}}_{\PGro}
    \PatPGroAdj: \text{\pmb{\Thorn}}_{\underline{\PGro}}
    \PatR: \text{\pmb{\Thorn}}_{\Rfree}
    \PatU: \text{\pmb{\Thorn}}_{\urate}
    \PatWGro: \text{\pmb{\Thorn}}_{\WGro}
    \PermGroFac: \pmb{\Phi}
    \PermGroFacAdj: \underline{\PermGroFac}
    \PermGroFacuAdj: \underline{\underline{\PermGroFac}}
    \PermGroRte: \varphi
    \PermLvl: \pLvl
    \PermLvlAgg: \PLvl
    \PermShk: \mathbf{\Psi}
    \PermShkAgg: \Psi
    \PermShkStd: \sigma_{\PermShk}
    \PermShkVar: \sigma^{2}_{\PermShk}
    \Plabor: P
    \Pop: L
    \PopE: \mathcal{E}
    \PopFac: \PopGro
    \PopGro: \Xi
    \PopLev: \pmb{N}
    \PopU: \mathcal{U}
    \PopnGroFac: \Xi
    \PopnGroRte: \xi
    \PopnLvl: \pmb{\mathrm{N}}
    \PostITC: \cancel{\zeta}
    \Price: \mathsf{P}
    \Prob: \mathbb{P}
    \ProdFunc: \mathrm{F}
    \PtyGro: \Phi
    \PtyLab: \mathrm{Z}
    \PtyLev: A
    \QFunc: \mathrm{Q}
    \QLev: Q
    \QLvl: \mathbf{Q}
    \RBoro: \bar{\Rfree}
    \RCpnd: \mathbf{R}
    \RFunc: \mathrm{R}
    \RGross: \breve{\mathsf{R}}
    \RLev: R
    \RLvl: \mathbf{R}
    \RNrm: \mathcal{R}
    \RPFac: \APFac_{\Rfree}
    \RPRte: \text{\thorn}_{\rfree}
    \RProd: \mathsf{R}
    \RSave: \underline{\Rfree}
    \Retire: \mathbb{R}
    \Rev: \Pi
    \RevFunc: \pmb{\Pi}
    \Rfree: \mathsf{R}
    \RfreeAgg: \Agg{\Rfree}
    \RfreeEff: \bar{\Rfree}
    \Risky: \mathbf{R}
    \RiskyAlt: \pmb{\mathfrak{R}}
    \Rnorm: \mathcal{R}
    \RnormWGro: \mathcal{R}_{\WGro}
    \Rport: \mathcal{R}
    \Rprod: \mathscr{R}
    \SDF: \MLev
    \SE: \SRat^{e}
    \SFunc: \mathrm{S}
    \SLev: S
    \SLevBF: \mathbf{S}
    \SLevE: \SLev^{e}
    \SLevU: \SLev^{u}
    \SLvl: \mathbf{S}
    \SNrm: S
    \SRat: S
    \SRatE: \SRat^{e}
    \SRatU: \SRat^{u}
    \STarg: \Target{\SRat}
    \STargE: \Target{\SRat}^{\null}
    \STargTarg: \Target{\Target{\SRat}}
    \SU: \SRat^{u}
    \Save: S
    \Seniority: \mathsf{X}
    \Severance: \kappa
    \SeverancePayment: \mathcal{S}
    \SeveranceRatio: \varsigma
    \Shk: \Phi
    \ShkLogZero: \cancel{\ShkMeanOne}
    \ShkLogZeroLog: \cancel{\ShkMeanOneLog}
    \ShkLogZeroLogStd: \sigma_{\cancel{\ShkMeanOneLog}}
    \ShkLogZeroLogVar: \sigma_{\cancel{\ShkMeanOneLog}}^{2}
    \ShkMeanOne: \Theta
    \ShkMeanOneLog: \theta
    \ShkMeanOneLogStd: \sigma_{\ShkMeanOneLog}
    \ShkMeanOneLogVar: \sigma^{2}_{\ShkMeanOneLog}
    \Steady: \bar
    \Stocks: S
    \Surplus: Z
    \TEat: \TEnd
    \TEatBak: \mathtt{q}
    \TEnd: T
    \TEndBak: \mathsf{p}
    \TFunc: \mathrm{T}
    \TLev: T
    \TLvl: \mathbf{T}
    \TMap: \mathscr{T}
    \TShk: \Xi
    \TShkEmp: \Theta
    \Target: \check
    \TargetNrm: \hat
    \Tax: \tau
    \TaxComb: \mathcal{T}
    \TaxCombInv: \mathcal{T}^{-1}
    \TaxCorp: \Large \tau
    \TaxFree: \cancel{\Tax}
    \TaxLev: T
    \TaxNetTrans: Z
    \TaxPaid: T
    \TaxRate: t
    \TaxUI: \tau
    \TermTime: T
    \TranShk: \Theta
    \TranShkAgg: \Theta
    \TranShkAll: \pmb{\xi}
    \TranShkEmp: \pmb{\xi}
    \TranShkEmpMin: \underline{\TranShkEmp}
    \TranShkStd: \sigma_{\TranShk}
    \TranShkVar: \sigma^{2}_{\TranShk}
    \UFunc: \mathrm{U}
    \ULev: U
    \ULvl: \mathbf{U}
    \VE: '{V}^{e}'
    \VEnd: \mathfrak{V}
    \VEndFunc: \mathfrak{V}
    \VFunc: \mathrm{V}
    \VInv: \Lambda
    \VLev: V
    \VLevFunc: \pmb{\mathrm{V}}
    \VLvl: \mathbf{V}
    \VNrm: V
    \VNum: V
    \VRat: V
    \VU: '{V}^{u}'
    \ValAlt: \mathcal{V}
    \Value: \mathrm{V}
    \WAll: O
    \WAllLev: \mathbf{O}
    \WAllRat: O
    \WBeg: \KLev
    \WEnd: \ALev
    \WEndRat: \ARat
    \WFunc: \mathrm{W}
    \WGro: \mathrm{G}
    \WGroPF: \mathrm{G}
    \WHum: \HLev
    \WLev: W
    \WLvl: \mathbf{W}
    \WMid: \BLev
    \WMkt: \MLev
    \WNet: X
    \WPre: K
    \WRat: O
    \WTot: \mathbf{O}
    \Wage: \mathsf{W}
    \Wealth: O
    \Wend: \ARat
    \Whum: \HRat
    \Wmid: \BRat
    \Work: \mathbb{W}
    \Wtot: O
    \XFer: X
    \XFunc: \mathrm{X}
    \XLev: X
    \XLvl: \mathbf{X}
    \XRat: X
    \XperGro: \mathsf{X}
    \YFunc: \mathrm{Y}
    \YLev: Y
    \YLevBF: \mathbf{Y}
    \YLvl: \mathbf{Y}
    \YNrm: Y
    \YRat: Y
    \ZFunc: \mathrm{Z}
    \ZLev: Z
    \ZLevBF: \mathbf{Z}
    \ZLvl: \mathbf{Z}
    \ZNrm: Z
    \ZRat: Z
    \aAgg: \mathsf{A}
    \aE: \aRat^{e}
    \aFunc: \mathrm{a}
    \aLev: a
    \aLevBF: \mathbf{a}
    \aLvl: \mathbf{a}
    \aMat: '[\mathrm{a}]'
    \aMin: \underline{\aRat}
    \aNrm: a
    \aRat: a
    \aRatBF: \pmb{a}
    \aSS: a
    \aTarg: \check{a}
    \aVec: \vec{\mathrm{a}}
    \aboveMin: \blacktriangle
    \adj: \mathrm{j}
    \adjPar: \omega
    \age: z
    \avg: \bar
    \bE: \bRat^{e}
    \bEndFunc: \mathfrak{b}
    \bFunc: \mathrm{b}
    \bLev: b
    \bLevBF: \mathbf{b}
    \bLevE: \bLev^{e}
    \bLevU: \bLev^{u}
    \bLvl: \mathbf{b}
    \bMat: '[\mathrm{\bNrm}]'
    \bMin: \underline{\bRat}
    \bNrm: b
    \bRat: b
    \bRatBF: \pmb{\mathrm{b}}
    \bRatE: '{b}^{e}'
    \bRatU: '{b}^{u}'
    \bTarg: \check{b}
    \bTargE: \check{b}^{e}
    \bTargTarg: \Target{\Target{\bRat}}
    \bTrgNrm: \TargetNrm{\bNrm}
    \bU: '{b}^{u}'
    \bVec: \vec{\mathrm{\bNrm}}
    \bqstNrm: e
    \cAgg: \pmb{C}
    \cE: \cRat^{e}
    \cEndFunc: \mathfrak{c}
    \cEss: '{c}^{e}'
    \cFunc: \mathrm{c}
    \cFuncAbove: \bar{\mathrm{c}}
    \cFuncBelow: \uline{\mathrm{c}}
    \cFuncMax: \bar{\bar{\mathrm{c}}}
    \cGroPF: \lambda
    \cLev: c
    \cLevBF: \mathbf{c}
    \cLevE: \cLev^{e}
    \cLevFunc: \pmb{\cFunc}
    \cLevU: \cLev^{u}
    \cLvl: \mathbf{c}
    \cMat: '[\mathrm{\cNrm}]'
    \cNrm: c
    \cP: \cons^{\prime}
    \cPDVFunc: \mathbb{C}
    \cPP: \cons^{\prime\prime}
    \cPPP: \cons^{\prime\prime\prime}
    \cRat: c
    \cRatBF: \pmb{c}
    \cRatE: \cRat^{e}
    \cRatU: \cRat^{u}
    \cTarg: \check{c}
    \cTargE: \check{c}^{e}
    \cTargTarg: \Target{\Target{\cRat}}
    \cU: \cRat^{u}
    \cVec: \vec{\mathrm{\cNrm}}
    \ccRat: \mathsf{c}
    \chiFunc: \pmb{\chi}
    \cons: c
    \corr: \varrho
    \cov: \textup{cov}
    \curr: '1'
    \dEndFunc: \mathfrak{d}
    \dFunc: \mathrm{d}
    \dLvl: \mathbf{d}
    \dNrm: d
    \dRat: d
    \debt: d
    \debtLim: \mathsf{d}
    \depr: \delta
    \deprRte: \delta
    \diePrb: \mathsf{d}
    \discRte: \tau
    \divGro: \mathsf{g}
    \dvdnd: d
    \eFunc: \mathrm{e}
    \eLvl: \mathbf{e}
    \eNrm: e
    \edvdnd: \grave{\dvdnd}
    \effUnits: X
    \ek: \lambda
    \empGro: \xi
    \empState: \xi
    \eprem: \varphi
    \erate: \cancel{\mho}
    \err: z
    \error: \epsilon
    \expend: \xi
    \fDist: \mathcal{f}
    \fFunc: \mathrm{f}
    \fLev: f
    \fLvl: \mathbf{f}
    \fNrm: f
    \fP: \mathrm{f}^{\prime}
    \fPP: \mathrm{f}^{\prime\prime}
    \gFunc: \mathrm{g}
    \gdpLev: \pmb{p}
    \gdpRat: p
    \govNW: n
    \govSpend: x
    \h: h
    \hEnd: \mathfrak{h}
    \hEndMin: \underline{\mathfrak{h}}
    \hFunc: \mathrm{h}
    \hLev: \pmb{h}
    \hLevBF: \mathbf{h}
    \hLvl: \mathbf{h}
    \hMin: \underline{\h}
    \hNrm: h
    \hRat: h
    \habit: h
    \headeright: ''
    \hours: \mathfrak{h}
    \iFunc: \mathrm{i}
    \iLev: i
    \iLvl: \mathbf{i}
    \iNrm: i
    \iRat: i
    \impg: \imath}_{\pGro
    \impr: \imath}_{\rfree
    \inc: y
    \inv: i
    \itc: \zeta
    \jFunc: \mathrm{j}
    \jLvl: \mathbf{j}
    \jNrm: j
    \kFunc: \mathrm{k}
    \kLev: k
    \kLevBF: \mathbf{k}
    \kLvl: \mathbf{k}
    \kNrm: k
    \kPrice: \mathsf{P}
    \kPriceAfterITC: \mathscr{P}
    \kRat: k
    \kTarg: \Target{k}
    \kTargE: \Target{k}^{e}
    \kap: k
    \kapRent: \varkappa
    \kapShare: \alpha
    \lEndFunc: \mathfrak{l}
    \lGro: \lambda
    \lLev: \ell
    \lLevBF: \pmb{\ell}
    \lRat: l
    \labShare: \nu
    \labor: \ell
    \leiShare: \zeta
    \leisure: z
    \livPrb: \cancel{\diePrb}
    \lqdt: \ell
    \mBalLog: \BalGroRte{m}
    \mBalLvl: \BalGroFac{m}
    \mE: \mRat^{e}
    \mEndFunc: \mathfrak{m}
    \mEss: \check{m}^{e}
    \mFunc: \mathrm{m}
    \mLev: m
    \mLevBF: \mathbf{m}
    \mLevE: \mLev^{e}
    \mLvl: \mathbf{m}
    \mMat: '[\mathrm{m}]'
    \mNrm: m
    \mRat: m
    \mRatBF: \pmb{\mathrm{m}}
    \mRatE: \mRat^{e}
    \mSS: \breve{m}
    \mTarg: \check{m}
    \mTrgNrm: \TargetNrm{m}
    \mU: '{m}^{u}'
    \mVec: \vec{\mathrm{m}}
    \nEndFunc: \mathfrak{n}
    \nFunc: \mathrm{n}
    \nIter: n
    \nLev: n
    \nRat: n
    \oLev: \pmb{o}
    \oLevBF: \mathbf{o}
    \oRat: o
    \pDead: \mathfrak{D}
    \pDeadRate: \grave{\cancel{\mathsf{d}}}
    \pDieRate: \grave{\mathsf{d}}
    \pDies: \mathsf{d}
    \pFunc: \mathrm{p}
    \pGro: \gamma
    \pGroAdj: \underline{\pGro}
    \pGrouAdj: \underline{\underline{\pGro}}
    \pLev: \pmb{p}
    \pLevBF: \mathbf{p}
    \pLives: \cancel{\pDies}
    \pLog: p
    \pLvl: \mathbf{p}
    \pNotZero: (1-\pZero)
    \pNrm: p
    \pPDVFunc: \mathbb{P}
    \pRat: p
    \pSav: \phi
    \pShk: \psi
    \pShkMin: \underline{\psi}
    \pZero: \wp
    \pat: \text{\thorn}
    \patpGro: \text{\thorn}_{\pGro}
    \patpGroAdj: \text{\thorn}_{\underline{\pGro}}
    \patpGrohat: \hat{\text{\thorn}}_{\pGro}
    \patr: \text{\thorn}_{\rfree}
    \patu: \text{\thorn}_{\urate}
    \patwGro: \text{\thorn}_{\wGro}
    \permGroFac: \Gamma
    \permGroFacAgg: \Phi
    \permGroFacInd: \pmb{\phi}
    \permGroRte: \gamma
    \permLvlAgg: \mathrm{P}
    \permLvlInd: \mathrm{p}
    \permShk: \psi
    \permShkAgg: \Psi
    \permShkInd: \psi
    \phiFunc: \digamma
    \popE: e
    \popGro: \xi
    \popRte: \popGro
    \power: \eta
    \prodFunc: \mathrm{f}
    \prud: \eta
    \prudEx: \omega
    \pshk: \psi
    \ptyGro: \phi
    \ptyLab: z
    \ptyLev: a
    \q: \koppa
    \rFunc: \mathrm{r}
    \rGross: \breve{\mathsf{r}}
    \rLvl: \mathbf{r}
    \rNrm: s
    \rProd: \mathsf{r}
    \rboro: \bar{\rfree}
    \rev: \pi
    \revFunc: \pmb{\pi}
    \rfree: \mathsf{r}
    \risky: \mathbf{r}
    \riskyAlt: \pmb{\mathfrak{r}}
    \riskyshare: \varsigma
    \rnorm: \mathit{r}
    \rnormwGro: \mathit{r}_{\wGro}
    \rport: \mathbb{r}
    \rprod: \mathscr{r}
    \rsave: \underline{\rfree}
    \sE: \sRat^{e}
    \sFunc: \mathrm{s}
    \sLev: s
    \sLevBF: \mathbf{s}
    \sLevE: \sLev^{e}
    \sLevU: \sLev^{u}
    \sLvl: \mathbf{s}
    \sNrm: s
    \sRat: s
    \sRatE: \sRat^{e}
    \sRatU: \sRat^{u}
    \sTarg: \Target{\sRat}
    \sTargE: \Target{\sRat}^{\null}
    \sTargTarg: \Target{\Target{\sRat}}
    \sU: \sRat^{u}
    \save: s
    \saveRate: \grave{s}
    \sdr: \mRat
    \seniority: \mathsf{x}
    \shk: \phi
    \shorttitle: ''
    \srate: \varsigma
    \stocks: s
    \straight: \Pi
    \surplus: z
    \tBak: \pmb{n}
    \tCurr: t
    \tFwd: n
    \tHor: \mathsf{n}
    \tHorOfm: \pmb{n}
    \tNext: t+1
    \tNow: t
    \tPrev: t-1
    \tSS: t
    \tShk: \xi
    \tShkAll: \xi
    \tShkEmp: \theta
    \tShkEmpMin: \underline{\theta}
    \tShkMat: '[\mathrm{\tShkEmp}]'
    \tTerm: T
    \tThen: \tau
    \tax: \tau
    \taxCorp: \tau
    \taxDep: \partial
    \taxNetTrans: z
    \timeRate: \vartheta
    \tinyAmount: \epsilon
    \tranShk: \theta
    \tranShkAgg: \Theta
    \tranShkAggStd: \sigma_{\tranShkAgg}
    \tranShkAggVar: \sigma^{2}_{\tranShkAgg}
    \tranShkEmp: \xi
    \tranShkEmpMin: \underline{\tranShkEmp}
    \tranShkInd: \theta
    \tranShkIndStd: \sigma_{\tranShkInd}
    \tranShkIndVar: \sigma^{2}_{\tranShkInd}
    \tshk: \xi
    \uFunc: \mathrm{u}
    \uInvEpShkuInv: \underline{\underline{\psi}}
    \uInvEuPermShk: \underline{\underline{\PermShk}}
    \uLev: u
    \uP: \mathrm{u}^{\prime}
    \uPDVFunc: \mathbb{U}
    \uPP: \mathrm{u}^{\prime\prime}
    \uPPP: \mathrm{u}^{\prime\prime\prime}
    \uPmt: \mu
    \undertitle: ''
    \unins: \zeta
    \urate: \mho
    \util: u
    \utilFunc: \mathrm{u}
    \vBeg: \upsilon
    \vBegFunc: \pmb{\upsilon}
    \vE: '{v}^{e}'
    \vEnd: \mathfrak{v}
    \vEndFunc: \mathfrak{v}
    \vEss: \check{v}^{e}
    \vFirm: \mathrm{e}
    \vFunc: \mathrm{v}
    \vInv: \scriptstyle \Lambda \displaystyle
    \vLev: v
    \vLevBF: \mathbf{v}
    \vLevFunc: \pmb{\mathrm{v}}
    \vLvl: \mathbf{v}
    \vNorm: \mathrm{w}
    \vNrm: v
    \vNum: v
    \vOpt: \tilde{\mathfrak{v}}
    \vOptAlt: \grave{\tilde{\mathfrak{v}}}
    \vRat: v
    \vTarg: \Target{\vRat}
    \vU: '{v}^{u}'
    \valfn: \mathrm{v}
    \vk: \lambda
    \wAll: o
    \wAllLev: \mathbf{o}
    \wAllRat: o
    \wBeg: \kLev
    \wEnd: \aLev
    \wEndRat: \aRat
    \wFunc: \mathrm{w}
    \wGro: \mathsf{g}
    \wHum: \hLev
    \wLev: \pmb{w}
    \wMid: \bLev
    \wMkt: \mLev
    \wNet: x
    \wPre: k
    \wRat: o
    \wTot: \mathbf{o}
    \wage: \mathsf{w}
    \wealth: o
    \wealthShare: \delta
    \weight: \omega
    \wend: \aRat
    \whum: \hRat
    \whumMin: \underline{\hRat}
    \wmid: \bRat
    \wmkt: \mLev
    \wtot: o
    \xFer: \chi
    \xFunc: \mathrm{x}
    \xLev: x
    \xMat: '[\mathrm{\xNrm}]'
    \xNrm: x
    \xRat: x
    \xpend: \xi
    \xperGro: \mathsf{x}
    \yFunc: \mathrm{y}
    \yLev: y
    \yLevBF: \mathbf{y}
    \yLvl: \mathbf{y}
    \yMat: '[\mathrm{\yNrm}]'
    \yNrm: y
    \yRat: y
    \yTarg: \check{y}
    \yTargE: \check{y}^{e}
    \yVec: \vec{\mathrm{\yNrm}}
    \zAgg: \pmb{Z}
    \zEndFunc: \mathfrak{z}
    \zFunc: \mathrm{z}
    \zLev: z
    \zLevBF: \pmb{z}
    \zLvl: \mathbf{z}
    \zNrm: z
    \zRat: z
