#!/bin/bash
# reproduce_utils.sh - Shared utilities for Life-Cycle-Prime-Time reproduction scripts
#
# Provides: logging, error handling, timing, benchmark recording.
# Source this file at the top of reproduce.sh and reproduce_min.sh.

# ============================================================================
# LOGGING
# ============================================================================

SCRIPT_START_TIME=$(date +%s)

LOG_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/logs"
LOG_FILE=""
LATEST_LOG="$LOG_DIR/latest.log"
LOGGING_ENABLED=false

log() {
    local level="$1"
    shift
    local message="$*"
    local timestamp
    timestamp=$(date '+%Y-%m-%d %H:%M:%S')
    local log_line="[$timestamp] [$level] $message"

    case "$level" in
        INFO)     echo "  $message" ;;
        SUCCESS)  echo "  [OK] $message" ;;
        WARNING)  echo "  [WARN] $message" >&2 ;;
        ERROR)    echo "  [ERROR] $message" >&2 ;;
        STEP)     echo ">> $message" ;;
        *)        echo "$message" ;;
    esac

    if [[ "$LOGGING_ENABLED" == true && -n "$LOG_FILE" ]]; then
        echo "$log_line" >> "$LOG_FILE"
    fi
}

init_logging() {
    local action="$1"  # e.g. "full" or "min"

    mkdir -p "$LOG_DIR"

    local ts
    ts=$(date +%Y%m%d-%H%M)
    local filename="${action}_${ts}.log"

    LOG_FILE="$LOG_DIR/$filename"
    LOGGING_ENABLED=true

    ln -sf "$(basename "$LOG_FILE")" "$LATEST_LOG"

    log INFO "==================================="
    log INFO "Life-Cycle-Prime-Time Reproduction"
    log INFO "Action: $action"
    log INFO "Working directory: $(pwd)"
    log INFO "Log file: $LOG_FILE"
    log INFO "==================================="
}

# ============================================================================
# ERROR HANDLING
# ============================================================================

error_handler() {
    local exit_code=$?
    local line_number=$1

    log ERROR "Script failed with exit code $exit_code at line $line_number"

    if [[ -n "$LOG_FILE" ]]; then
        log ERROR "Check log for details: $LOG_FILE"
        echo ""
        echo "========================================"
        echo "Last 20 log entries:"
        echo "========================================"
        tail -20 "$LOG_FILE" 2>/dev/null || echo "(Unable to read log file)"
        echo "========================================"
    fi
}

trap 'error_handler $LINENO' ERR

# ============================================================================
# BENCHMARKING
# ============================================================================

BENCHMARK_ENABLED="${BENCHMARK:-true}"
BENCHMARK_START_TIME=""
BENCHMARK_START_ISO=""
REPRODUCE_KIND=""

benchmark_start() {
    local kind="$1"  # "full" or "min"
    REPRODUCE_KIND="$kind"

    if [[ "$BENCHMARK_ENABLED" == "true" ]]; then
        BENCHMARK_START_TIME=$(date +%s)
        BENCHMARK_START_ISO=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
        log INFO "Benchmarking enabled - timing started"
    fi
}

benchmark_end() {
    if [[ "$BENCHMARK_ENABLED" != "true" ]]; then
        return 0
    fi
    if [[ -z "$BENCHMARK_START_TIME" ]]; then
        return 0
    fi

    local exit_status=$1

    # Only record benchmarks for successful runs
    if [[ "$exit_status" -ne 0 ]]; then
        log WARNING "Run failed (exit $exit_status) - benchmark not saved"
        return 0
    fi

    local end_time
    end_time=$(date +%s)
    local end_iso
    end_iso=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
    local duration=$((end_time - BENCHMARK_START_TIME))

    local kind="${REPRODUCE_KIND:-unknown}"

    # Build filename: {kind}_YYYYMMDD-HHMM_{duration}s.json
    local ts
    ts=$(date -r "$BENCHMARK_START_TIME" '+%Y%m%d-%H%M' 2>/dev/null || date -d "@$BENCHMARK_START_TIME" '+%Y%m%d-%H%M' 2>/dev/null || date '+%Y%m%d-%H%M')
    local duration_str
    duration_str=$(printf "%06d" "$duration")
    local filename="${kind}_${ts}_${duration_str}s.json"

    local repo_root
    repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
    local benchmark_dir="$repo_root/reproduce/benchmarks/results/autogenerated"
    mkdir -p "$benchmark_dir"

    local output_file="$benchmark_dir/$filename"

    # Capture system info via Python helper
    local capture_script="$repo_root/reproduce/capture_system_info.py"
    local sysinfo_json=""
    if [[ -f "$capture_script" ]]; then
        local temp_sysinfo="/tmp/lcpt_bench_$$_sysinfo.json"
        python3 "$capture_script" --pretty --output "$temp_sysinfo" 2>/dev/null || true

        if [[ -f "$temp_sysinfo" && -s "$temp_sysinfo" ]]; then
            if head -1 "$temp_sysinfo" | grep -q "^{" 2>/dev/null; then
                # Extract inner fields (strip outer braces) for embedding
                sysinfo_json=$(sed '1d; $d' "$temp_sysinfo" | sed 's/^/  /')
            fi
        fi
        rm -f "$temp_sysinfo"
    fi

    if [[ -n "$sysinfo_json" ]]; then
        cat > "$output_file" << EOF
{
  "benchmark_version": "1.0.0",
  "benchmark_id": "${kind}_${ts}",
  "timestamp": "$BENCHMARK_START_ISO",
  "timestamp_end": "$end_iso",
  "reproduction_kind": "${kind}",
  "exit_status": $exit_status,
  "duration_seconds": $duration,
${sysinfo_json},
  "metadata": {
    "user": "${USER:-unknown}",
    "session_id": "$$",
    "ci": ${CI:-false},
    "notes": ""
  }
}
EOF
    else
        cat > "$output_file" << EOF
{
  "benchmark_version": "1.0.0",
  "benchmark_id": "${kind}_${ts}",
  "timestamp": "$BENCHMARK_START_ISO",
  "timestamp_end": "$end_iso",
  "reproduction_kind": "${kind}",
  "exit_status": $exit_status,
  "duration_seconds": $duration,
  "system": {},
  "environment": {},
  "git": {},
  "metadata": {
    "user": "${USER:-unknown}",
    "session_id": "$$",
    "ci": ${CI:-false},
    "notes": ""
  }
}
EOF
    fi

    # Symlink latest.json
    local results_dir
    results_dir="$(dirname "$benchmark_dir")"
    ln -sf "autogenerated/$filename" "$results_dir/latest.json"

    log SUCCESS "Benchmark saved: $output_file"
    log INFO "Duration: ${duration}s"
}

# ============================================================================
# SUMMARY
# ============================================================================

print_summary() {
    local exit_code=$1
    local elapsed=$(($(date +%s) - SCRIPT_START_TIME))

    echo ""
    echo "=========================================="
    if [[ "$exit_code" -eq 0 ]]; then
        echo "  REPRODUCTION SUCCEEDED"
    else
        echo "  REPRODUCTION FAILED (exit code $exit_code)"
    fi
    echo "  Kind:     ${REPRODUCE_KIND:-unknown}"
    echo "  Duration: ${elapsed}s"
    if [[ -n "$LOG_FILE" ]]; then
        echo "  Log:      $LOG_FILE"
    fi
    echo "=========================================="
    echo ""
}

# EXIT trap: print summary and record benchmark
_reproduce_exit_handler() {
    local exit_code=$?
    # Disable error trapping inside the exit handler
    set +e
    print_summary $exit_code
    benchmark_end $exit_code
}
trap '_reproduce_exit_handler' EXIT
